[package]
name = "aoc2021day13"
version = "0.1.0"
authors = ["Chris Blom <chrisblom@chrisblom.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
