[package]
name = "aoc2021day16"
version = "0.1.0"
authors = ["Chris Blom <chrisblom@chrisblom.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
nom = "7"